#pragma once

#include "core/profiler/core.h"

#include <cstdint>


#if defined(ENG_PROFILING_ENABLED)
#include <tracy/Tracy.hpp>


#define ENG_PROFILE_FRAME(NAME)         FrameMarkNamed(NAME)

#define ENG_PROFILE_BEGIN_FRAME(NAME)   FrameMarkStart(NAME)
#define ENG_PROFILE_END_FRAME(NAME)     FrameMarkEnd(NAME)


#define ENG_PROFILE_SCOPED_MARKER_N(NAME, LABEL)                    ZoneNamedN(NAME, LABEL, true)
#define ENG_PROFILE_SCOPED_MARKER_NC_U32(NAME, LABEL, COLOR)        ZoneNamedNC(NAME, LABEL, COLOR, true)
#define ENG_PROFILE_SCOPED_MARKER_NC(NAME, LABEL, R8, G8, B8, A8)   ENG_PROFILE_SCOPED_MARKER_NC_U32(NAME, LABEL, _ENG_PROFILE_MAKE_COLOR_U32(R8, G8, B8, A8))

#define ENG_PROFILE_SCOPED_MARKER(LABEL)                    ZoneScopedN(LABEL)
#define ENG_PROFILE_SCOPED_MARKER_C_U32(LABEL, COLOR)       ZoneScopedNC(LABEL, COLOR)
#define ENG_PROFILE_SCOPED_MARKER_C(LABEL, R8, G8, B8, A8)  ENG_PROFILE_SCOPED_MARKER_C_U32(LABEL, _ENG_PROFILE_MAKE_COLOR_U32(R8, G8, B8, A8))

// For very short-lived events that is called frequently
#define ENG_PROFILE_TRANSIENT_SCOPED_MARKER(NAME, LABEL)    ZoneTransientN(NAME, LABEL, true)
// For very short-lived events that is called frequently
#define ENG_PROFILE_TRANSIENT_SCOPED_MARKER_C_U32(NAME, LABEL, COLOR)       ZoneTransientNC(NAME, LABEL, COLOR, true)
#define ENG_PROFILE_TRANSIENT_SCOPED_MARKER_C(NAME, LABEL, R8, G8, B8, A8)  ENG_PROFILE_TRANSIENT_SCOPED_MARKER_C_U32(NAME, LABEL, _ENG_PROFILE_MAKE_COLOR_U32(R8, G8, B8, A8))


#define ENG_PROFILE_BEGIN_MARKER_N_SCOPE(NAME, LABEL)   \
    {                                                   \
        ENG_PROFILE_SCOPED_MARKER_N(NAME, LABEL)

#define ENG_PROFILE_BEGIN_MARKER_NC_U32_SCOPE(NAME, LABEL, COLOR)   \
    {                                                               \
        ENG_PROFILE_SCOPED_MARKER_NC_U32(NAME, LABEL, COLOR)

#define ENG_PROFILE_BEGIN_MARKER_NC_SCOPE(NAME, LABEL, R8, G8, B8, A8)  \
    ENG_PROFILE_BEGIN_MARKER_NC_U32_SCOPE(NAME, LABEL, _ENG_PROFILE_MAKE_COLOR_U32(R8, G8, B8, A8))

#define ENG_PROFILE_BEGIN_MARKER_SCOPE(LABEL)   \
    {                                           \
        ENG_PROFILE_SCOPED_MARKER(LABEL)

#define ENG_PROFILE_BEGIN_MARKER_C_U32_SCOPE(LABEL, COLOR)   \
    {                                                        \
        ENG_PROFILE_SCOPED_MARKER_C_U32(LABEL, COLOR)

#define ENG_PROFILE_BEGIN_MARKER_C_SCOPE(LABEL, R8, G8, B8, A8)   \
    ENG_PROFILE_BEGIN_MARKER_C_U32_SCOPE(LABEL, _ENG_PROFILE_MAKE_COLOR_U32(R8, G8, B8, A8))

#define ENG_PROFILE_BEGIN_TRANSIENT_MARKER_SCOPE(NAME, LABEL)   \
    {                                                           \
        ENG_PROFILE_TRANSIENT_SCOPED_MARKER(NAME, LABEL)

#define ENG_PROFILE_BEGIN_TRANSIENT_MARKER_C_U32_SCOPE(NAME, LABEL, COLOR) \
    {                                                                      \
        ENG_PROFILE_TRANSIENT_SCOPED_MARKER_C_U32(NAME, LABEL, COLOR)

#define ENG_PROFILE_BEGIN_TRANSIENT_MARKER_C_SCOPE(NAME, LABEL, R8, G8, B8, A8) \
    ENG_PROFILE_BEGIN_TRANSIENT_MARKER_C_U32_SCOPE(NAME, LABEL, _ENG_PROFILE_MAKE_COLOR_U32(R8, G8, B8, A8))

#define ENG_PROFILE_END_MARKER_SCOPE()  \
    }


#define ENG_PROFILE_MARKER_N_TEXT(NAME, FMT, ...)  ZoneTextVF(NAME, FMT, __VA_ARGS__)
#define ENG_PROFILE_MARKER_N_VALUE(NAME, VALUE)    ZoneValueV(NAME, VALUE)

#define ENG_PROFILE_MARKER_TEXT(FMT, ...)  ZoneTextF(FMT, __VA_ARGS__)
#define ENG_PROFILE_MARKER_VALUE(VALUE)    ZoneValue(VALUE)

#define ENG_PROFILE_IS_MARKER_ACTIVE() ZoneIsActive
#define ENG_PROFILE_IS_MARKER_N_ACTIVE(NAME) ZoneIsActiveV(NAME)


#define ENG_PROFILE_LOG_C_U32(TEXT, COLOR) TracyMessageC(TEXT, strlen(TEXT), COLOR)
#define ENG_PROFILE_LOG_C(TEXT, R8, G8, B8, A8) ENG_PROFILE_LOG_C_U32(TEXT, _ENG_PROFILE_MAKE_COLOR_U32(R8, G8, B8, A8))
#else
#define ENG_PROFILE_FRAME(NAME)

#define ENG_PROFILE_BEGIN_FRAME(NAME)
#define ENG_PROFILE_END_FRAME(NAME)

#define ENG_PROFILE_SCOPED_MARKER_N(NAME, LABEL)
#define ENG_PROFILE_SCOPED_MARKER_NC_U32(NAME, LABEL, COLOR)
#define ENG_PROFILE_SCOPED_MARKER_NC(NAME, LABEL, R8, G8, B8, A8)

#define ENG_PROFILE_SCOPED_MARKER(LABEL)
#define ENG_PROFILE_SCOPED_MARKER_C_U32(LABEL, COLOR)
#define ENG_PROFILE_SCOPED_MARKER_C(LABEL, R8, G8, B8, A8)

// For very short-lived events that is called frequently
#define ENG_PROFILE_TRANSIENT_SCOPED_MARKER(NAME, LABEL)
// For very short-lived events that is called frequently
#define ENG_PROFILE_TRANSIENT_SCOPED_MARKER_C_U32(NAME, LABEL, COLOR)
#define ENG_PROFILE_TRANSIENT_SCOPED_MARKER_C(NAME, LABEL, R8, G8, B8, A8)

#define ENG_PROFILE_BEGIN_MARKER_N_SCOPE(NAME, LABEL)

#define ENG_PROFILE_BEGIN_MARKER_NC_U32_SCOPE(NAME, LABEL, COLOR)

#define ENG_PROFILE_BEGIN_MARKER_NC_SCOPE(NAME, LABEL, R8, G8, B8, A8)

#define ENG_PROFILE_BEGIN_MARKER_SCOPE(LABEL)

#define ENG_PROFILE_BEGIN_MARKER_C_U32_SCOPE(LABEL, COLOR)

#define ENG_PROFILE_BEGIN_MARKER_C_SCOPE(LABEL, R8, G8, B8, A8)

#define ENG_PROFILE_BEGIN_TRANSIENT_MARKER_SCOPE(NAME, LABEL)

#define ENG_PROFILE_BEGIN_TRANSIENT_MARKER_C_U32_SCOPE(NAME, LABEL, COLOR)

#define ENG_PROFILE_BEGIN_TRANSIENT_MARKER_C_SCOPE(NAME, LABEL, R8, G8, B8, A8)

#define ENG_PROFILE_END_MARKER_SCOPE()

#define ENG_PROFILE_MARKER_N_TEXT(NAME, FMT, ...)
#define ENG_PROFILE_MARKER_N_VALUE(NAME, VALUE)

#define ENG_PROFILE_MARKER_TEXT(FMT, ...)
#define ENG_PROFILE_MARKER_VALUE(VALUE)

#define ENG_PROFILE_IS_MARKER_ACTIVE()
#define ENG_PROFILE_IS_MARKER_N_ACTIVE(NAME)

#define ENG_PROFILE_LOG_C_U32(TEXT, COLOR)
#define ENG_PROFILE_LOG_C(TEXT, R8, G8, B8, A8)
#endif
